### ISSUE TITLE
Daemon Rescanning Stuck on CLI

### ISSUE THREAD

**Issue by kaks25** [buidl1/zundernet#14]
The app gives a timeout that cannot reach the RPC port, have to press Enter to continue rescanning.

![Rescan](https://user-images.githubusercontent.com/65034388/156893181-8f9637d6-9a55-48c1-b355-89624a87aaf6.PNG)

**Comment by buidl1** [comment]
I also get this msg sometimes but it comes from the deamon, so nothing I can do - I just display what deamon tells. However misleading it should not be an issue - will sync after some time.
